AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub www.takamoto.dev
      Type: A
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: "d392d1kf550oit.cloudfront.net."
        EvaluateTargetHealth: false
      HostedZoneId: Z08348221VRCAVEWA569X # takamot.dev
