#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all, expects="0+"
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults expects=0
Resources:

  SNSTopic:
    Type: AWS::SNS::Topic

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      #! https://docs.aws.amazon.com/ja_jp/awsaccountbilling/latest/aboutv2/budgets-sns-policy.html の内容そのまま
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: BudgetsSNSPublishingPermissions
            Effect: Allow
            Principal:
              Service: budgets.amazonaws.com
            Action: SNS:Publish
            Resource:
              Ref: SNSTopic
      Topics:
        - Ref: SNSTopic
