#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all, expects="0+"
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults expects=0
Resources:

  MonthlyBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetLimit:
          Amount: #@ data.values.budget.limit_usd
          Unit: USD
        #! BudgetName にマルチバイト文字を利用すると CloudFormation の Web UI 上で
        #!  "???" のような表示になってうまくリンク先に飛べないので注意
        BudgetName: Monthly Budget
        BudgetType: COST
        TimeUnit: MONTHLY
        CostTypes:
          IncludeCredit: false
          IncludeDiscount: true
          IncludeOtherSubscription: true
          IncludeRecurring: true
          IncludeRefund: false
          IncludeSubscription: true
          IncludeSupport: true
          IncludeTax: true
          IncludeUpfront: true
          UseAmortized: false
          UseBlended: false
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: #@ data.values.budget.threshold_percent
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: #@ data.values.budget.email
            - SubscriptionType: SNS
              Address:
                Ref: SNSTopic
