#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all, expects="0+"
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults expects=0
Resources:

  ChatBotSlackChannelConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: MonthlyBudgetNotification-Chatbot
      IamRoleArn:
        Fn::GetAtt: ChatBotRole.Arn
      LoggingLevel: NONE
      SlackChannelId: #@ data.values.budget.slack.channel_id
      SlackWorkspaceId: #@ data.values.budget.slack.workspace_id
      SnsTopicArns:
        - Ref: SNSTopic

  ChatBotRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Chatbot role for slack notification
      Path: "/budget/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: chatbot.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: ChatbotNortificationsOnly-Policy
          #! https://docs.aws.amazon.com/chatbot/latest/adminguide/chatbot-iam-policies.html
          #! "The AWS Chatbot Notification Permissions IAM policy" そのまま
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                Resource: "*"
