#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults expects=0
Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Sub: blog.takamoto.dev
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: d392d1kf550oit.cloudfront.net.
        EvaluateTargetHealth: false
      HostedZoneId:  #@ data.values.global_values.hosted_zones.takamoto_dev.id
