#@ load("@ytt:overlay", "overlay")
#@ load("tags.lib.yaml", "tags")
#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults expects=0
Resources:

  NetworkVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags: #@ tags("vpc")

  NetworkIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: #@ tags("igw")

  NetworkAttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: NetworkVPC
      InternetGatewayId:
        Ref: NetworkIGW

  NetworkPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId:
        Ref: NetworkVPC
      CidrBlock: 10.0.1.0/24
      Tags: #@ tags("public-subnet")

  NetworkPublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: NetworkVPC
      Tags: #@ tags("public-subnet-routetable")

  NetworkInternetRouteForPublicSubnetRouteTable:
    Type: AWS::EC2::Route
    DependsOn:
      - NetworkAttachIGW
    Properties:
      RouteTableId:
        Ref: NetworkPublicSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: NetworkIGW

  NetworkAssociatePublicSubnetRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: NetworkPublicSubnet
      RouteTableId:
        Ref: NetworkPublicSubnetRouteTable
