#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults expects=0
Resources:

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: minecraft.takamoto.dev
      Type: A
      TTL: '900'
      HostedZoneId: #@ data.values.global_values.hosted_zones.takamoto_dev.id
      ResourceRecords:
        - Ref: EC2EIP
