name: Deploy AWS CloudFormation Stacks
on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Deploy CloudFormation stack name'
        type: choice
        options:
        - MinecraftServer

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./aws

jobs:
  deploy:
    environment:
      name: production
    name: Deploy CloudFormation Stacks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install CDK Dependency
        working-directory: ./aws
        run: npm install -g aws-cdk

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install poetry
        run: |
          curl -sSL curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::715861157510:role/github-actions-oidc/github-actions-oidc_aws-account-management
          aws-region: ap-northeast-1
      - name: Show diff
        run: poetry run cdk diff ${{ inputs.stack }}
      - name: Execute deploy
        run: poetry run cdk deploy --require-approval never ${{ inputs.stack }}

