name: Deploy AWS Base Cloudformation Stacks
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Cloudformation Stacks
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy budget Cloudformation Stack
        env:
          STACK_NAME: budget
        run: |
          aws cloudformation deploy \
            --stack-name ${STACK_NAME} \
            --template-file ${STACK_NAME}.yaml \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM
